package boggledApp;


/**
* boggledApp/bannedAccountException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class bannedAccountException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public bannedAccountException ()
  {
    super(bannedAccountExceptionHelper.id());
  } // ctor

  public bannedAccountException (String _msg)
  {
    super(bannedAccountExceptionHelper.id());
    msg = _msg;
  } // ctor


  public bannedAccountException (String $reason, String _msg)
  {
    super(bannedAccountExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class bannedAccountException
