package boggledApp;

/**
* boggledApp/bannedAccountExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class bannedAccountExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.bannedAccountException value = null;

  public bannedAccountExceptionHolder ()
  {
  }

  public bannedAccountExceptionHolder (boggledApp.bannedAccountException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.bannedAccountExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.bannedAccountExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.bannedAccountExceptionHelper.type ();
  }

}
