package boggledApp;

/**
* boggledApp/BoggledCallBackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Thursday, May 16, 2024 2:17:14 PM SGT
*/

public final class BoggledCallBackHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.BoggledCallBack value = null;

  public BoggledCallBackHolder ()
  {
  }

  public BoggledCallBackHolder (boggledApp.BoggledCallBack initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.BoggledCallBackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.BoggledCallBackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.BoggledCallBackHelper.type ();
  }

}
