package boggledApp;


/**
* boggledApp/BoggledCallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Thursday, May 16, 2024 2:17:14 PM SGT
*/

public interface BoggledCallBackOperations 
{
  void playerJoinedRoom (String username) throws boggledApp.roomDoesntExistException;
  void startNotif (String username);
  void endGameNotif (String username);
  void playerLeftNotif (String username);
} // interface BoggledCallBackOperations
