package boggledApp;


/**
* boggledApp/BoggledCallBackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Thursday, May 16, 2024 2:17:14 PM SGT
*/

public abstract class BoggledCallBackPOA extends org.omg.PortableServer.Servant
 implements boggledApp.BoggledCallBackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("playerJoinedRoom", new java.lang.Integer (0));
    _methods.put ("startNotif", new java.lang.Integer (1));
    _methods.put ("endGameNotif", new java.lang.Integer (2));
    _methods.put ("playerLeftNotif", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // boggledApp/BoggledCallBack/playerJoinedRoom
       {
         try {
           String username = in.read_string ();
           this.playerJoinedRoom (username);
           out = $rh.createReply();
         } catch (boggledApp.roomDoesntExistException $ex) {
           out = $rh.createExceptionReply ();
           boggledApp.roomDoesntExistExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // boggledApp/BoggledCallBack/startNotif
       {
         String username = in.read_string ();
         this.startNotif (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // boggledApp/BoggledCallBack/endGameNotif
       {
         String username = in.read_string ();
         this.endGameNotif (username);
         out = $rh.createReply();
         break;
       }

       case 3:  // boggledApp/BoggledCallBack/playerLeftNotif
       {
         String username = in.read_string ();
         this.playerLeftNotif (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:boggledApp/BoggledCallBack:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BoggledCallBack _this() 
  {
    return BoggledCallBackHelper.narrow(
    super._this_object());
  }

  public BoggledCallBack _this(org.omg.CORBA.ORB orb) 
  {
    return BoggledCallBackHelper.narrow(
    super._this_object(orb));
  }


} // class BoggledCallBackPOA
