package boggledApp;

/**
* boggledApp/BoggledHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class BoggledHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.Boggled value = null;

  public BoggledHolder ()
  {
  }

  public BoggledHolder (boggledApp.Boggled initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.BoggledHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.BoggledHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.BoggledHelper.type ();
  }

}
