package boggledApp;


/**
* boggledApp/BoggledCallBack.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Thursday, May 16, 2024 2:17:14 PM SGT
*/

public interface BoggledCallBack extends BoggledCallBackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BoggledCallBack
