package boggledApp;


/**
* boggledApp/failedLogOutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class failedLogOutException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public failedLogOutException ()
  {
    super(failedLogOutExceptionHelper.id());
  } // ctor

  public failedLogOutException (String _msg)
  {
    super(failedLogOutExceptionHelper.id());
    msg = _msg;
  } // ctor


  public failedLogOutException (String $reason, String _msg)
  {
    super(failedLogOutExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class failedLogOutException
