package boggledApp;


/**
* boggledApp/forcedLogOutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class forcedLogOutException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public forcedLogOutException ()
  {
    super(forcedLogOutExceptionHelper.id());
  } // ctor

  public forcedLogOutException (String _msg)
  {
    super(forcedLogOutExceptionHelper.id());
    msg = _msg;
  } // ctor


  public forcedLogOutException (String $reason, String _msg)
  {
    super(forcedLogOutExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class forcedLogOutException
