package boggledApp;


/**
* boggledApp/invalidWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class invalidWordException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public invalidWordException ()
  {
    super(invalidWordExceptionHelper.id());
  } // ctor

  public invalidWordException (String _msg)
  {
    super(invalidWordExceptionHelper.id());
    msg = _msg;
  } // ctor


  public invalidWordException (String $reason, String _msg)
  {
    super(invalidWordExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class invalidWordException
