package boggledApp;

/**
* boggledApp/invalidWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class invalidWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.invalidWordException value = null;

  public invalidWordExceptionHolder ()
  {
  }

  public invalidWordExceptionHolder (boggledApp.invalidWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.invalidWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.invalidWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.invalidWordExceptionHelper.type ();
  }

}
