package boggledApp;


/**
* boggledApp/LongSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class LongSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public LongSequenceHolder ()
  {
  }

  public LongSequenceHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.LongSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.LongSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.LongSequenceHelper.type ();
  }

}
