package boggledApp;


/**
* boggledApp/mapTimeAndIDHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Sunday, May 12, 2024 3:04:18 PM SGT
*/

abstract public class mapTimeAndIDHelper
{
  private static String  _id = "IDL:boggledApp/mapTimeAndID:1.0";

  public static void insert (org.omg.CORBA.Any a, boggledApp.mapTimeAndID that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static boggledApp.mapTimeAndID extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "roomID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "remainingTime",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (boggledApp.mapTimeAndIDHelper.id (), "mapTimeAndID", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static boggledApp.mapTimeAndID read (org.omg.CORBA.portable.InputStream istream)
  {
    boggledApp.mapTimeAndID value = new boggledApp.mapTimeAndID ();
    value.roomID = istream.read_long ();
    value.remainingTime = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, boggledApp.mapTimeAndID value)
  {
    ostream.write_long (value.roomID);
    ostream.write_long (value.remainingTime);
  }

}
