package boggledApp;

/**
* boggledApp/outOfTimeExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class outOfTimeExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.outOfTimeException value = null;

  public outOfTimeExceptionHolder ()
  {
  }

  public outOfTimeExceptionHolder (boggledApp.outOfTimeException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.outOfTimeExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.outOfTimeExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.outOfTimeExceptionHelper.type ();
  }

}
