package boggledApp;


/**
* boggledApp/outOfTimeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class outOfTimeException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public outOfTimeException ()
  {
    super(outOfTimeExceptionHelper.id());
  } // ctor

  public outOfTimeException (String _msg)
  {
    super(outOfTimeExceptionHelper.id());
    msg = _msg;
  } // ctor


  public outOfTimeException (String $reason, String _msg)
  {
    super(outOfTimeExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class outOfTimeException
