package boggledApp;

/**
* boggledApp/roomDoesntExistExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class roomDoesntExistExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.roomDoesntExistException value = null;

  public roomDoesntExistExceptionHolder ()
  {
  }

  public roomDoesntExistExceptionHolder (boggledApp.roomDoesntExistException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.roomDoesntExistExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.roomDoesntExistExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.roomDoesntExistExceptionHelper.type ();
  }

}
