package boggledApp;


/**
* boggledApp/sameWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class sameWordException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public sameWordException ()
  {
    super(sameWordExceptionHelper.id());
  } // ctor

  public sameWordException (String _msg)
  {
    super(sameWordExceptionHelper.id());
    msg = _msg;
  } // ctor


  public sameWordException (String $reason, String _msg)
  {
    super(sameWordExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class sameWordException
