package boggledApp;

/**
* boggledApp/sameWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class sameWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.sameWordException value = null;

  public sameWordExceptionHolder ()
  {
  }

  public sameWordExceptionHolder (boggledApp.sameWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.sameWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.sameWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.sameWordExceptionHelper.type ();
  }

}
