package boggledApp;

/**
* boggledApp/tieScoreExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class tieScoreExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.tieScoreException value = null;

  public tieScoreExceptionHolder ()
  {
  }

  public tieScoreExceptionHolder (boggledApp.tieScoreException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.tieScoreExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.tieScoreExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.tieScoreExceptionHelper.type ();
  }

}
