package boggledApp;


/**
* boggledApp/tieScoreException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class tieScoreException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public tieScoreException ()
  {
    super(tieScoreExceptionHelper.id());
  } // ctor

  public tieScoreException (String _msg)
  {
    super(tieScoreExceptionHelper.id());
    msg = _msg;
  } // ctor


  public tieScoreException (String $reason, String _msg)
  {
    super(tieScoreExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class tieScoreException
