package boggledApp;

/**
* boggledApp/userAlreadyLogInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class userAlreadyLogInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public boggledApp.userAlreadyLogInException value = null;

  public userAlreadyLogInExceptionHolder ()
  {
  }

  public userAlreadyLogInExceptionHolder (boggledApp.userAlreadyLogInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boggledApp.userAlreadyLogInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boggledApp.userAlreadyLogInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boggledApp.userAlreadyLogInExceptionHelper.type ();
  }

}
