package boggledApp;


/**
* boggledApp/usernameAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbaIDL.idl
* Tuesday, May 28, 2024 5:11:50 PM SGT
*/

public final class usernameAlreadyExistsException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public usernameAlreadyExistsException ()
  {
    super(usernameAlreadyExistsExceptionHelper.id());
  } // ctor

  public usernameAlreadyExistsException (String _msg)
  {
    super(usernameAlreadyExistsExceptionHelper.id());
    msg = _msg;
  } // ctor


  public usernameAlreadyExistsException (String $reason, String _msg)
  {
    super(usernameAlreadyExistsExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class usernameAlreadyExistsException
