/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Server.servant;
import Utilities.DriverManagers;
import Utilities.user;
import boggledApp.Boggled;
import boggledApp.BoggledHelper;
import boggledApp.usernameAlreadyExistsException;
import org.omg.CORBA.ORB;
import org.omg.CosNaming.NameComponent;
import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author RAVEN
 */
public class AdminGUI extends javax.swing.JFrame {
    private ORB orb;
    /**
     * Creates new form Test
     */
    public AdminGUI() {
        initComponents();
       getContentPane().setBackground(Color.WHITE);
       UserTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        materialTabbed1 = new MaterialTabbed();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOpen = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfSecs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statuslabel = new javax.swing.JLabel();
        btnSet = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchTF = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        JButton btnRefresh = new JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnUpdateUsername = new javax.swing.JButton();
        updateUsernameTF = new javax.swing.JTextField();
        JTextArea updateUsernameTA = new JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        materialTabbed1.setBackground(new java.awt.Color(119, 176, 170));

        jPanel2.setBackground(new java.awt.Color(119, 176, 170));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Open Server");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setText("Close Server");

        btnOpen.setBackground(new java.awt.Color(136, 171, 142));
        btnOpen.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnOpen.setForeground(new java.awt.Color(255, 255, 255));
        btnOpen.setText("Open");
        btnOpen.addActionListener(evt -> {
            SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    DriverManagers.closeAllRoom();
                    try {
                        statuslabel.setText("Server Online");
                        String[] args = {"orbd", "-ORBInitialPort", "1050", "-ORBInitialHost", "localhost"};
                         orb = ORB.init(args, null);
                        POA rootpoa = POAHelper.narrow(orb.resolve_initial_references("RootPOA"));
                        rootpoa.the_POAManager().activate();
                        servant servantImpl = new servant();
                        org.omg.CORBA.Object ref = rootpoa.servant_to_reference(servantImpl);
                        Boggled href = BoggledHelper.narrow(ref);
                        org.omg.CORBA.Object objRef = orb.resolve_initial_references("NameService");
                        NamingContextExt ncRef = NamingContextExtHelper.narrow(objRef);
                        String name = "Boggled";
                        NameComponent path[] = ncRef.to_name(name);
                        ncRef.rebind(path, href);
                        orb.run();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return null;
                }
            };
            worker.execute();

        });
        btnRefresh.setText("Refresh");  // Add this block
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTable();
            }
        });

        btnClose.setBackground(new java.awt.Color(163, 67, 67));
        btnClose.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(evt -> {
            SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    try {
                        DriverManagers.closeAllRoom();
                        statuslabel.setText("Server Offline");
                        orb.shutdown(false);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return null;
                }

            };
            worker.execute(); // Start SwingWorker

        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setText("Server Status:");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setText("Set Timer");

        tfSecs.setBackground(new java.awt.Color(227, 254, 247));
        tfSecs.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        tfSecs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("secs");

        statuslabel.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        statuslabel.setText("Close");

        btnSet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSet.setText("Set");

btnSet.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            secs = Integer.parseInt(tfSecs.getText());
            System.out.println("Time set to: " + secs + " seconds");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "It should be number format(seconds)", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
});
        btnDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SwingUtilities.invokeLater(() -> {
                    SwingUtilities.invokeLater(() -> {
                        int response = JOptionPane.showConfirmDialog(
                                null,
                                "Are you sure you want to delete this server?",
                                "Warning",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.WARNING_MESSAGE);
                        if (response == JOptionPane.YES_OPTION) {
                            int selectedRow = jTable1.getSelectedRow();
                            if (selectedRow != -1) {
                                String username = (String) jTable1.getValueAt(selectedRow, 0);
                                Boolean status = DriverManagers.deleteUser(username);
                                if (status) {
                                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                    model.removeRow(selectedRow);
                                    JOptionPane.showMessageDialog(null, "User deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Please select a user to delete.", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    });
                });

            }
        });
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpen))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statuslabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfSecs, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnSet)))
                .addContainerGap(624, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(statuslabel))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnOpen))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnClose))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSecs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSet)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Menu", jPanel2);

        jPanel3.setBackground(new java.awt.Color(119, 176, 170));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Username", "HighScore", "Status"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSearch.setText("Search");

        btnDelete.setText("Delete User");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateUsername)
                        .addComponent(btnRefresh)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearch)
                                        .addComponent(btnDelete)
                                        .addComponent(btnUpdateUsername)
                                        .addComponent(updateUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdateUsername)
                                .addComponent(btnRefresh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnUpdateUsername.setText("Update Username");
        btnUpdateUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String newUsername = updateUsernameTF.getText();
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) {
                    String oldUsername = (String) jTable1.getValueAt(selectedRow, 0);
                    Boolean status = null;
                    if (oldUsername.equals(newUsername)) {
                        JOptionPane.showMessageDialog(null, "Your inserted username is match with the old one! please try another one", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    try {
                        status = DriverManagers.updateUsername(oldUsername, newUsername);
                    } catch (usernameAlreadyExistsException e) {
                        JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    if (status) {
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.setValueAt(newUsername, selectedRow, 0);
                        JOptionPane.showMessageDialog(null, "Username updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to update username.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please select a user to update.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });






        materialTabbed1.addTab("Accounts", jPanel3);

        jPanel1.setBackground(new java.awt.Color(119, 176, 170));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel7.setText("Username");

        btnAdd.setText("Add");

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel10.setText("Password");
      btnAdd.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
              String username = UsernameTF.getText();
              String password = jPasswordField1.getText();
              user u = new user(username, password);
              try {
                  DriverManagers.Register(u);
                  JOptionPane.showMessageDialog(null, "Successful registration", "Success", JOptionPane.INFORMATION_MESSAGE);
              } catch (usernameAlreadyExistsException ex) {
                  JOptionPane.showMessageDialog(null, "Username already taken! please try again", "Invalid registration", JOptionPane.ERROR_MESSAGE);
              }
          }
      });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnAdd)))
                .addContainerGap(693, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Add User", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
btnSearch.addActionListener(new java.awt.event.ActionListener() {

    @Override
    public void actionPerformed(ActionEvent e) {
        searchUser();
    }
});
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }
    public void searchUser() {
        SwingWorker<List<user>, String[]> worker = new SwingWorker<List<user>, String[]>() {
            @Override
            protected List<user> doInBackground() throws Exception {
                List<user> users = new ArrayList<>();
                String username = searchTF.getText().toLowerCase();
                ArrayList<user> listOfUsers = DriverManagers.searchUser(username);
                users.addAll(listOfUsers);
                for (user user : users) {
                    String[] userData = {user.getUsername(), user.getHighScore(), user.getIsActive()};
                    publish(userData);
                }
                return users;
            }

            @Override
            protected void process(List<String[]> chunks) {
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.setRowCount(0);
                if (chunks.isEmpty()) {
                    tableModel.setRowCount(0);
                } else {
                    for (String[] entry : chunks) {
                        tableModel.addRow(entry);
                    }
                }
            }

            @Override
            protected void done() {
                try {
                    List<user> users = get();
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }
            }
        };
        worker.execute();
    }

    public void UserTable() {
        SwingWorker<List<user>, String[]> worker = new SwingWorker<List<user>, String[]>() {
            @Override
            protected List<user> doInBackground() throws Exception {
                List<user> users = new ArrayList<>();
                ArrayList<user> listOfUsers = DriverManagers.getUsers();
                users.addAll(listOfUsers);
                for (user user : users) {
                    String[] userData = {user.getUsername(),user.getHighScore(),user.getIsActive()};
                    publish(userData);
                }
                return users;
            }

            @Override
            protected void process(List<String[]> chunks) {
                DefaultTableModel tableModel = (DefaultTableModel) AdminGUI.getjTable1().getModel();
                tableModel.setRowCount(0);
                for (String[] entry : chunks) {
                    tableModel.addRow(entry);
                }
            }

            @Override
            protected void done() {
                try {
                    List<user> users = get();

                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }
            }
        };
        worker.execute();
    }
    private static int secs;

    public static int getSecs() {
        return secs;
    }

    public static JTable getjTable1() {
        return jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSet;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private MaterialTabbed materialTabbed1;
    private javax.swing.JTextField searchTF;
    private javax.swing.JLabel statuslabel;
    private javax.swing.JTextField tfSecs;
    JButton btnUpdateUsername = new JButton();
    JTextField updateUsernameTF = new JTextField();
    // End of variables declaration//GEN-END:variables
}
