package View;

/**
 *
 * @author lawrencesin
 */
public class LoaderMultiplayer extends javax.swing.JFrame {

    /**
     * Creates new form LoaderMultiplayer
     */
    public LoaderMultiplayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        fourthPlayerName = new javax.swing.JLabel();
        fourthPlayerPic = new javax.swing.JLabel();
        iconInput1 = new javax.swing.JLabel();
        firstPlayerName1 = new javax.swing.JLabel();
        secondPlayerPic1 = new javax.swing.JLabel();
        secondPlayerName1 = new javax.swing.JLabel();
        thirdPlayerPic1 = new javax.swing.JLabel();
        thirdPlayerName1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Katari", 1, 15)); // NOI18N
        jLabel2.setText("Player 4:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 120, 40));

        jLabel5.setFont(new java.awt.Font("Katari", 1, 15)); // NOI18N
        jLabel5.setText("Player 1:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 40));

        jLabel6.setFont(new java.awt.Font("Katari", 1, 15)); // NOI18N
        jLabel6.setText("Player 2:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 40));

        jLabel7.setFont(new java.awt.Font("Katari", 1, 15)); // NOI18N
        jLabel7.setText("Player 3:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 40));

        startButton.setBackground(new java.awt.Color(249, 249, 249));
        startButton.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        startButton.setText("START");
        startButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 176, 61));

        fourthPlayerName.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        fourthPlayerName.setText("???");
        jPanel1.add(fourthPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 230, 50));

        fourthPlayerPic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(fourthPlayerPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 50, 50));

        iconInput1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(iconInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 50, 50));

        firstPlayerName1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        firstPlayerName1.setText("???");
        jPanel1.add(firstPlayerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 230, 50));

        secondPlayerPic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(secondPlayerPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 50, 50));

        secondPlayerName1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        secondPlayerName1.setText("???");
        jPanel1.add(secondPlayerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 230, 50));

        thirdPlayerPic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(thirdPlayerPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 50, 50));

        thirdPlayerName1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        thirdPlayerName1.setText("???");
        jPanel1.add(thirdPlayerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 230, 50));

        backButton.setBackground(new java.awt.Color(103, 111, 95));
        backButton.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, -1, -1));

        jLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel1.setText("ROOM: ???");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/greenbg1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaderMultiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaderMultiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaderMultiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaderMultiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaderMultiplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JLabel firstPlayerName1;
    private javax.swing.JLabel fourthPlayerName;
    private javax.swing.JLabel fourthPlayerPic;
    private javax.swing.JLabel iconInput1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel secondPlayerName1;
    private javax.swing.JLabel secondPlayerPic1;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel thirdPlayerName1;
    private javax.swing.JLabel thirdPlayerPic1;
    // End of variables declaration
}
